# =============================================================================
# OmniDomain — Terraform Outputs
# Values needed to configure the Streamlit app and Nextflow
# =============================================================================

output "compute_bucket" {
  description = "S3 bucket for raw reads and Nextflow work directory"
  value       = aws_s3_bucket.compute.bucket
}

output "results_bucket" {
  description = "S3 bucket for pipeline outputs"
  value       = aws_s3_bucket.results.bucket
}

output "ecr_repository_url" {
  description = "ECR URL — push your Docker image here"
  value       = aws_ecr_repository.nextflow.repository_url
}

output "batch_job_queue" {
  description = "AWS Batch job queue ARN — set as AWS_BATCH_QUEUE in .env"
  value       = aws_batch_job_queue.main.arn
}

output "batch_job_definition" {
  description = "AWS Batch job definition ARN — set as AWS_BATCH_JOB_DEFINITION in .env"
  value       = aws_batch_job_definition.nextflow.arn
}

output "efs_id" {
  description = "EFS filesystem ID — mount this to populate tool databases"
  value       = aws_efs_file_system.databases.id
}

output "efs_dns" {
  description = "EFS DNS name for mounting"
  value       = aws_efs_file_system.databases.dns_name
}

output "streamlit_access_key_id" {
  description = "AWS access key ID for the Streamlit app — add to .env"
  value       = aws_iam_access_key.streamlit.id
  sensitive   = true
}

output "streamlit_secret_access_key" {
  description = "AWS secret access key for the Streamlit app — add to .env"
  value       = aws_iam_access_key.streamlit.secret
  sensitive   = true
}

output "env_template" {
  description = "Copy this into your .env file"
  sensitive   = true
  value       = <<-ENV
    # OmniDomain — .env (generated by Terraform)
    # Run: terraform output -raw env_template > .env

    AWS_ACCESS_KEY_ID=${aws_iam_access_key.streamlit.id}
    AWS_SECRET_ACCESS_KEY=${aws_iam_access_key.streamlit.secret}
    AWS_REGION=${var.aws_region}

    OMNI_COMPUTE_BUCKET=${aws_s3_bucket.compute.bucket}
    OMNI_RESULTS_BUCKET=${aws_s3_bucket.results.bucket}
    OMNI_BASE_OUTDIR=s3://${aws_s3_bucket.results.bucket}

    AWS_BATCH_QUEUE=${aws_batch_job_queue.main.name}
    AWS_BATCH_JOB_DEFINITION=${aws_batch_job_definition.nextflow.name}

    DATABASE_URL=postgresql://omni:CHANGE_ME@localhost:5432/omnidb
  ENV
}
