"""initial schema

Revision ID: 503f3bfedf3a
Revises: 
Create Date: 2026-06-11 16:20:30.459394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '503f3bfedf3a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('org', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('pipeline', sa.String(length=50), nullable=False),
    sa.Column('sample_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'SUBMITTED', 'RUNNING', 'COMPLETED', 'FAILED', name='run_status_enum'), nullable=False),
    sa.Column('tsv_row', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('base_outdir', sa.String(length=255), nullable=True),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.Column('job_id', sa.String(length=255), nullable=True),
    sa.Column('job_name', sa.String(length=255), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resume', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_runs_pipeline'), 'runs', ['pipeline'], unique=False)
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    op.create_index(op.f('ix_runs_user_id'), 'runs', ['user_id'], unique=False)
    op.create_table('run_status_history',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'SUBMITTED', 'RUNNING', 'COMPLETED', 'FAILED', name='run_status_enum'), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_run_status_history_run_id'), 'run_status_history', ['run_id'], unique=False)
    op.create_table('uploads',
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('s3_uri', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('upload_id')
    )
    op.create_index(op.f('ix_uploads_run_id'), 'uploads', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploads_run_id'), table_name='uploads')
    op.drop_table('uploads')
    op.drop_index(op.f('ix_run_status_history_run_id'), table_name='run_status_history')
    op.drop_table('run_status_history')
    op.drop_index(op.f('ix_runs_user_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_status'), table_name='runs')
    op.drop_index(op.f('ix_runs_pipeline'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
