name: FungalFlow Pipeline Test

on:
  push:
    branches: [ test-fungalflow ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        
      - name: Check FungalFlow syntax
        run: |
          nextflow compile nextflow/fungalflow/main.nf
          
      - name: Pipeline Dry-Run
        run: |
          nextflow run nextflow/fungalflow/main.nf -dry-run